"""Minimal ProjectFacts contract package for tender-basic."""

from .models import (
    CandidateFact,
    DocxParagraphLocator,
    DocxTableLocator,
    FactStatus,
    FieldName,
    Locator,
    PdfLocator,
    PdfTableLocator,
    ProjectFacts,
    ProjectFields,
    ResolvedFact,
    SourceDocument,
    SourceType,
    SemanticCandidateProposal,
)
from .format_extractor import (
    BidFormatTemplate,
    FormatElement,
    extract_bid_format,
    extract_format_template,
)
from .semantic_candidates import (
    apply_semantic_candidate_proposals,
    build_fact_gap_packet,
    validate_semantic_candidate_proposal,
)
from .page_layout import (
    EditableBlank,
    EditableBlankKind,
    EditableBlankRenderStyle,
    BlankRepresentationKind,
    SourceLineSpacingMode,
    SourceLineSpacingProfile,
    infer_semantic_line_spacing,
    FormBlock,
    FormRowGeometry,
    ListLayoutGroup,
    ParagraphLayout,
    ParagraphLayoutRole,
    ParagraphTabStop,
)
from .numbering import NumberingOwnership, SourceNumberToken, parse_source_number_token
from .dynamic_requirements import (
    RequirementIndex,
    SourceRequirementUnit,
    build_requirement_index,
)
from .dynamic_review import (
    DynamicReviewItem,
    DynamicReviewPlan,
    build_dynamic_review_plan,
    dynamic_review_qa,
)

__all__ = [
    "CandidateFact",
    "BidFormatTemplate",
    "DocxParagraphLocator",
    "DocxTableLocator",
    "FactStatus",
    "FieldName",
    "FormatElement",
    "Locator",
    "PdfLocator",
    "PdfTableLocator",
    "ProjectFacts",
    "ProjectFields",
    "ResolvedFact",
    "SourceDocument",
    "SourceType",
    "SemanticCandidateProposal",
    "apply_semantic_candidate_proposals",
    "build_fact_gap_packet",
    "extract_bid_format",
    "extract_format_template",
    "validate_semantic_candidate_proposal",
    "EditableBlank",
    "EditableBlankKind",
    "EditableBlankRenderStyle",
    "BlankRepresentationKind",
    "SourceLineSpacingMode",
    "SourceLineSpacingProfile",
    "infer_semantic_line_spacing",
    "FormBlock",
    "FormRowGeometry",
    "ListLayoutGroup",
    "ParagraphLayout",
    "ParagraphLayoutRole",
    "ParagraphTabStop",
    "NumberingOwnership",
    "SourceNumberToken",
    "parse_source_number_token",
    "DynamicReviewItem",
    "DynamicReviewPlan",
    "RequirementIndex",
    "SourceRequirementUnit",
    "build_dynamic_review_plan",
    "build_requirement_index",
    "dynamic_review_qa",
]
