"""Source-owned and generated numbering primitives.

Numbering is deliberately modelled separately from Word styles. A source
document may use a Heading style for navigation while its visible prefix
remains literal source text. Only content explicitly generated by the
system may opt into Word's automatic numbering.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from enum import Enum
from typing import Any


class NumberingOwnership(str, Enum):
    """Who owns the visible numbering of a paragraph."""

    SOURCE_LITERAL = "SOURCE_LITERAL"
    GENERATED_AUTO = "GENERATED_AUTO"
    NONE = "NONE"


_MARKER_RE = re.compile(
    r"^\s*(?P<marker>"
    r"附[表件录][一二三四五六七八九十百千万零〇\d]+|"
    r"[一二三四五六七八九十百千万零〇]+[、．.]|"
    r"\d+(?:\.\d+)*[、．.]|"
    r"\d+[)）]|"
    r"[（(][一二三四五六七八九十百千万零〇]+[）)]|"
    r"[（(]\d+[）)]|"
    r"[①-⑳]"
    r")(?P<separator>[ \t\u00a0\u3000]*)"
)


def _level_and_family(marker: str) -> tuple[int | None, str]:
    if re.fullmatch(r"附[表件录][一二三四五六七八九十百千万零〇\d]+", marker):
        return None, "APPENDIX_LABEL"
    if re.fullmatch(r"[一二三四五六七八九十百千万零〇]+[、．.]", marker):
        return 1, "CHINESE_CLAUSE"
    if re.fullmatch(r"[（(][一二三四五六七八九十百千万零〇]+[）)]", marker):
        return 2, "CHINESE_PAREN"
    decimal = re.fullmatch(r"(\d+(?:\.\d+)*)([、．.]|[)）])", marker)
    if decimal:
        level = decimal.group(1).count(".") + 1
        family = "DECIMAL_BODY" if decimal.group(2) in "、)）" else "DECIMAL"
        return level, family
    if re.fullmatch(r"[（(]\d+[）)]", marker):
        return 2, "DECIMAL_PAREN"
    if re.fullmatch(r"[①-⑳]", marker):
        return 1, "CIRCLED"
    return None, "UNKNOWN"


@dataclass(frozen=True)
class SourceNumberToken:
    """The source-visible numbering token retained through reconstruction."""

    raw_prefix: str
    normalized_level_hint: int | None
    numbering_family: str
    separator_after_prefix: str
    source_locator: Any = None
    confidence: float = 1.0
    ownership: NumberingOwnership = NumberingOwnership.SOURCE_LITERAL

    @property
    def marker(self) -> str:
        return self.raw_prefix[: len(self.raw_prefix) - len(self.separator_after_prefix)]

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["ownership"] = self.ownership.value
        locator = self.source_locator
        if hasattr(locator, "model_dump"):
            data["source_locator"] = locator.model_dump(mode="json")
        elif hasattr(locator, "as_dict"):
            data["source_locator"] = locator.as_dict()
        elif hasattr(locator, "__dict__"):
            data["source_locator"] = dict(locator.__dict__)
        return data


def parse_source_number_token(
    text: str,
    *,
    source_locator: Any = None,
    confidence: float = 1.0,
    ownership: NumberingOwnership = NumberingOwnership.SOURCE_LITERAL,
) -> SourceNumberToken | None:
    """Parse, but never normalize, a source-visible prefix."""

    match = _MARKER_RE.match(text or "")
    if match is None:
        return None
    marker = match.group("marker")
    separator = match.group("separator")
    level, family = _level_and_family(marker)
    return SourceNumberToken(
        raw_prefix=marker + separator,
        normalized_level_hint=level,
        numbering_family=family,
        separator_after_prefix=separator,
        source_locator=source_locator,
        confidence=max(0.0, min(1.0, float(confidence))),
        ownership=ownership,
    )


def marker_info(text: str) -> tuple[str, str]:
    """Backward-compatible marker helper that does not expose spacing."""

    token = parse_source_number_token(text)
    if token is None:
        return "", text or ""
    match = _MARKER_RE.match(text or "")
    assert match is not None
    return token.marker, (text or "")[match.end():].lstrip()


def prefix_punctuation(prefix: str) -> str:
    """Return only punctuation/sign characters from a visible prefix."""

    return "".join(character for character in prefix if not character.isalnum() and not character.isspace())


__all__ = [
    "NumberingOwnership",
    "SourceNumberToken",
    "marker_info",
    "parse_source_number_token",
    "prefix_punctuation",
]
