"""Source-first Word style and numbering architecture.

The source-format model deliberately remains PDF/geometry oriented.  This
module is the bridge between that model and an editable Word document:

* the supplied Danyang fixture contributes editable style infrastructure and
  optional numbering machinery for content generated by this system;
* source spans are clustered by semantic role to produce a per-tender visual
  profile; and
* source-owned visible numbering remains literal source text.

The module does not resolve facts and does not change the source-format or
ProjectFacts contracts.
"""

from __future__ import annotations

import hashlib
import re
from collections import Counter, defaultdict
from contextvars import ContextVar
from dataclasses import asdict, dataclass, field
from pathlib import Path
from statistics import median
from typing import Any, Iterable
from zipfile import ZipFile

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor
from lxml import etree

from .source_font_policy import normalize_pdf_font_name
from .word_safe_xml import clean_bootstrap
from .source_format import SourceFormatTemplate, TypographyRole
from .page_layout import infer_semantic_line_spacing
from .numbering import (
    NumberingOwnership,
    SourceNumberToken,
    marker_info,
    parse_source_number_token,
)


FIXTURE_DEFAULT_PATH = Path(
    r"D:\Documents\WPG\02_招投标AI开发\输出格式\danyang-v1.1-numbering-sanity-fixture-v5.docx"
)
W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
W = {"w": W_NS}

#: Round 5.6 rendered-glyph weight verdicts, scoped to one profile inference.
_VISUAL_WEIGHTS: ContextVar[dict[str, bool]] = ContextVar("tender_visual_weights", default={})


ALIGNMENT_VALUES = {
    "left": WD_ALIGN_PARAGRAPH.LEFT,
    "center": WD_ALIGN_PARAGRAPH.CENTER,
    "right": WD_ALIGN_PARAGRAPH.RIGHT,
    "justify": WD_ALIGN_PARAGRAPH.JUSTIFY,
}

STYLE_BASELINES = {
    "Tender Body": "Normal",
    "Tender Body First Line": "正文（首行缩进两字）",
    "Tender Body Center": "正文居中",
    "Tender Body Right": "正文靠右",
    "Tender Body No Indent": "Normal",
    "Tender Signature Block": "正文（首行缩进两字）",
    "Tender Form Label": "Normal",
    "Tender Chapter Title": "正文居中",
    "Tender Cover Project Title": "正文居中",
    "Tender Document Title": "正文居中",
    "Tender TOC Title": "正文居中",
    "Tender TOC 1": "Normal",
    "Tender TOC 2": "Normal",
    "Tender TOC 3": "Normal",
    "Table Text": "Table Text",
    "Tender Table Header": "Table Text",
    "Tender Table Label": "Table Text",
    "Tender Table Value": "Table Text",
    "Tender Table Numeric": "Table Text",
    "Tender Table Unit": "Table Text",
}


@dataclass
class RoleStyle:
    """Visual parameters for one semantic Word style role."""

    font_east_asia: str = "宋体"
    font_ascii: str = "Times New Roman"
    source_font_raw: str = ""
    font_size: float = 10.5
    font_weight: str = "regular"
    paragraph_alignment: str = "left"
    line_spacing: float = 12.0
    space_before: float = 0.0
    space_after: float = 0.0
    left_indent: float = 0.0
    right_indent: float = 0.0
    first_line_indent: float = 0.0
    hanging_indent: float = 0.0
    page_break_before: bool = False
    keep_with_next: bool = False
    keep_lines: bool = False
    outline_level: int | None = None
    based_on: str = "Normal"
    evidence_count: int = 0
    evidence_weight: int = 0

    @property
    def bold(self) -> bool:
        return self.font_weight == "bold"

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["bold"] = self.bold
        return data


@dataclass
class TenderStyleProfile:
    """Per-tender style profile inferred from clustered source evidence."""

    source_file: str = ""
    roles: dict[str, RoleStyle] = field(default_factory=dict)
    body_list_formats: dict[int, str] = field(default_factory=dict)
    body_list_source_markers: dict[int, str] = field(default_factory=dict)
    heading_numbering_formats: dict[int, str] = field(default_factory=dict)
    heading_numbering_source_markers: dict[int, str] = field(default_factory=dict)
    heading_numbering_family: str = "SOURCE_LITERAL"
    body_list_numbering_family: str = "SOURCE_LITERAL"
    numbering_exception_reason: str | None = None
    inference_method: str = "dominant semantic-role clusters weighted by source character count"

    def role(self, name: str, fallback: str = "Tender Body") -> RoleStyle:
        return self.roles.get(name) or self.roles.get(fallback) or RoleStyle()

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["roles"] = {name: role.as_dict() for name, role in self.roles.items()}
        return data


@dataclass(frozen=True)
class ParagraphSemantic:
    role: str
    heading_level: int | None = None
    list_level: int | None = None
    numbering_family: str | None = None
    marker: str = ""
    evidence: str = ""
    numbering_ownership: NumberingOwnership = NumberingOwnership.NONE
    source_number_token: SourceNumberToken | None = None
    classification_status: str = "CLASSIFIED"

    @property
    def style_name(self) -> str:
        if self.role == "HEADING":
            return f"Heading {self.heading_level or 1}"
        if self.role == "BODY_LIST":
            return f"Tender Body List {(self.list_level or 0) + 1}"
        return {
            "CHAPTER_TITLE": "Tender Chapter Title",
            "COVER_PROJECT_TITLE": "Tender Cover Project Title",
            "DOCUMENT_TITLE": "Tender Document Title",
            "TOC_TITLE": "Tender TOC Title",
            "TOC_1": "Tender TOC 1",
            "TOC_2": "Tender TOC 2",
            "TOC_3": "Tender TOC 3",
            "FORM_LABEL": "Tender Form Label",
            "SIGNATURE_BLOCK": "Tender Signature Block",
            "BODY_FIRST_LINE": "Tender Body First Line",
            "BODY_CENTER": "Tender Body Center",
            "BODY_RIGHT": "Tender Body Right",
            "BODY_NO_INDENT": "Tender Body No Indent",
            "TABLE_TEXT": "Table Text",
        }.get(self.role, "Tender Body")


def _compact(text: str) -> str:
    return re.sub(r"\s+", "", text or "")


def heading_level_for_marker(marker: str) -> int | None:
    if not marker:
        return None
    if re.fullmatch(r"[一二三四五六七八九十百千万零〇]+[、．.]", marker):
        return 1
    if re.fullmatch(r"[（(][一二三四五六七八九十百千万零〇]+[）)]", marker):
        return 2
    decimal = re.fullmatch(r"(\d+(?:\.\d+)*)[．.]", marker)
    if decimal:
        return min(9, 2 + decimal.group(1).count("."))
    return None


def body_list_level_for_marker(marker: str) -> int:
    if re.fullmatch(r"[（(]\d+[）)]", marker):
        return 1
    if re.fullmatch(r"\d+\.\d+[．.]", marker):
        return 1
    if re.fullmatch(r"\d+\.\d+\.\d+[．.]", marker):
        return 2
    if re.fullmatch(r"[（(][一二三四五六七八九十]+[）)]", marker):
        return 1
    return 0


def _titleish(text: str) -> bool:
    compact = _compact(text).strip()
    if not compact or len(compact) > 65:
        return False
    return not bool(re.search(r"[，。；：？！!?]", compact))


def _toc_pages(template: SourceFormatTemplate) -> set[int]:
    pages: set[int] = set()
    for page in template.source_pages:
        if any(_compact(paragraph.text) in {"目录", "目 录"} for paragraph in page.paragraphs):
            pages.add(page.page)
    return pages


def _toc_key(text: str) -> str:
    """Normalize a TOC entry only for structural comparison, never output."""

    compact = _compact(text)
    compact = re.sub(r"[.．。·…]+\d+$", "", compact)
    return compact


def _toc_entries(template: SourceFormatTemplate) -> set[str]:
    entries: set[str] = set()
    pages = _toc_pages(template)
    for page in template.source_pages:
        if page.page not in pages:
            continue
        for paragraph in page.paragraphs:
            text = paragraph.text or ""
            if _compact(text) in {"目录", "目 录"}:
                continue
            entries.add(_toc_key(text))
            marker, remainder = marker_info(text)
            if marker:
                entries.add(_toc_key(remainder))
    return {entry for entry in entries if entry}


_STRUCTURAL_WORDS = (
    "投标函", "响应函", "证明", "委托书", "授权", "承诺书", "资格",
    "保证金", "技术方案", "施工组织设计", "定标相关资料", "项目情况",
    "偏离表", "报价表", "文件格式", "格式自拟",
)


def _is_generic_table_fragment(remainder: str) -> bool:
    compact = _compact(remainder)
    return bool(
        compact in {"表", "图", "附表", "附图", "表格"}
        or re.fullmatch(r"(?:表|图)[一二三四五六七八九十百\d]{0,3}", compact)
    )


def _has_bold_run(item: Any) -> bool:
    return any(
        bool(getattr(run, "bold", False))
        or str(getattr(run, "font_weight_role", "")).lower() == "bold"
        for run in getattr(getattr(item, "source", None), "runs", []) or []
    )


def _neighbor_has_heading_signal(item: Any, neighboring_items: list[Any] | None) -> bool:
    if not neighboring_items:
        return False
    try:
        index = next(index for index, candidate in enumerate(neighboring_items) if candidate is item)
    except StopIteration:
        return False
    for candidate in neighboring_items[max(0, index - 1): index + 2]:
        if candidate is item:
            continue
        text = getattr(candidate, "logical_text", "") or ""
        if getattr(candidate, "kind", "") == "Heading" and _titleish(text):
            return True
    return False


def _heading_evidence(
    item: Any,
    remainder: str,
    *,
    layout_classification: str,
    toc_entries: set[str],
    neighboring_items: list[Any] | None,
) -> tuple[int, list[str]]:
    """Score combined structural evidence; a number prefix is only one signal."""

    score = 0
    evidence: list[str] = []
    source = getattr(item, "source", None)
    source_alignment = getattr(source, "alignment", "")
    font_size = float(getattr(item, "font_size_pt", 0.0) or 0.0)
    if getattr(item, "kind", "") == "Heading":
        score += 2
        evidence.append("heading_candidate_geometry")
    if layout_classification == "CHAPTER_DIVIDER":
        score += 3
        evidence.append("chapter_page_structure")
    if getattr(item, "alignment_hint", "") == "center" or source_alignment == "center":
        score += 2
        evidence.append("center_alignment")
    if font_size >= 16:
        score += 2
        evidence.append("large_font")
    elif font_size >= 13:
        score += 1
        evidence.append("heading_sized_font")
    if _has_bold_run(item):
        score += 1
        evidence.append("bold_font_role")
    if _titleish(remainder):
        score += 1
        evidence.append("title_semantics")
    if _toc_key(remainder) in toc_entries or _toc_key(getattr(item, "logical_text", "")) in toc_entries:
        score += 4
        evidence.append("toc_correspondence")
    if any(word in _compact(remainder) for word in _STRUCTURAL_WORDS):
        score += 1
        evidence.append("structural_semantics")
    if getattr(item, "kind", "") == "List":
        score -= 2
        evidence.append("list_candidate_penalty")
    if re.search(r"[，。；：？！!?]", _compact(remainder)):
        score -= 3
        evidence.append("sentence_punctuation_penalty")
    if len(_compact(remainder)) > 65:
        score -= 3
        evidence.append("long_text_penalty")
    if _neighbor_has_heading_signal(item, neighboring_items):
        score += 1
        evidence.append("neighbor_structure")
    if _is_generic_table_fragment(remainder):
        score -= 3
        evidence.append("generic_table_fragment_penalty")
    return score, evidence


def classify_paragraph(
    item: Any,
    page: Any,
    *,
    layout_classification: str = "",
    toc_pages: set[int] | None = None,
    toc_entries: set[str] | None = None,
    neighboring_items: list[Any] | None = None,
) -> ParagraphSemantic:
    """Classify source content using geometry, semantics, TOC and neighbors.

    The preliminary ``item.kind`` remains useful evidence, but it is never
    sufficient to promote a numbered fragment to a navigational Heading.
    """

    toc_pages = toc_pages or set()
    toc_entries = toc_entries or set()
    text = item.logical_text or ""
    compact = _compact(text)
    marker, remainder = marker_info(text)
    token = parse_source_number_token(
        text,
        source_locator=getattr(getattr(item, "source", None), "locator", None),
    )
    ownership = token.ownership if token else NumberingOwnership.NONE
    family = token.numbering_family if token else None
    source_role = getattr(getattr(item, "source", None), "typography_role", TypographyRole.BODY)
    source_role = getattr(source_role, "value", source_role)

    if compact in {"目录", "目 录"}:
        return ParagraphSemantic("TOC_TITLE", evidence="exact contents-page title")
    if page.page in toc_pages:
        if marker:
            level = (token.normalized_level_hint if token and token.normalized_level_hint else 3)
            return ParagraphSemantic(
                f"TOC_{min(level, 3)}", marker=marker,
                numbering_family=family,
                numbering_ownership=ownership,
                source_number_token=token,
                evidence="same-page contents entry; excluded from outline",
            )
        return ParagraphSemantic("TOC_1", evidence="same-page contents text; excluded from outline")

    # Some source PDFs label cover blocks as generic headings even though they
    # are document metadata, not navigational sections. Use the cover-page
    # geometry plus the title text to keep them in explicit non-numbered roles.
    if layout_classification == "COVER_PAGE":
        if (
            ("投标文件" in compact or compact in {"响应文件", "响应文件格式"})
            and _titleish(text)
            and len(compact) <= 20
        ):
            return ParagraphSemantic("DOCUMENT_TITLE", evidence="cover-page document title")
        if "项目" in compact and _titleish(text):
            return ParagraphSemantic("COVER_PROJECT_TITLE", evidence="cover-page project title")

    if source_role == TypographyRole.COVER_CHAPTER.value or layout_classification == "CHAPTER_DIVIDER":
        return ParagraphSemantic("CHAPTER_TITLE", evidence="source chapter divider role")
    if source_role == TypographyRole.COVER_PROJECT_TITLE.value:
        return ParagraphSemantic("COVER_PROJECT_TITLE", evidence="source cover title cluster")
    if source_role == TypographyRole.COVER_DOCUMENT_TITLE.value:
        return ParagraphSemantic("DOCUMENT_TITLE", evidence="source cover document-title cluster")

    if item.kind == "FormRow":
        return ParagraphSemantic("SIGNATURE_BLOCK", evidence="geometry form row")

    score, heading_evidence = _heading_evidence(
        item,
        remainder,
        layout_classification=layout_classification,
        toc_entries=toc_entries,
        neighboring_items=neighboring_items,
    )
    heading_candidate = bool(marker and remainder and _titleish(remainder)) or item.kind == "Heading"
    if heading_candidate and score >= 4 and not (
        _is_generic_table_fragment(remainder) and "toc_correspondence" not in heading_evidence
    ):
        level = token.normalized_level_hint if token and token.normalized_level_hint else 1
        return ParagraphSemantic(
            "HEADING", heading_level=min(9, max(1, level)),
            marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            evidence=";".join(heading_evidence),
        )

    if marker and (item.kind == "List" or re.match(r"^(?:\d+[、.)）]|[（(]\d+[）)])", text.strip())):
        return ParagraphSemantic(
            "BODY_LIST", list_level=min(3, body_list_level_for_marker(marker)),
            marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            classification_status=(
                "HEADING_CLASSIFICATION_NEEDS_REVIEW"
                if heading_candidate else "CLASSIFIED"
            ),
            evidence="sentence/list marker; excluded from outline",
        )

    if token is not None and heading_candidate:
        # Keep the source text visible and out of navigation until combined
        # evidence resolves the structural role. This is intentionally not a
        # compliance or fact status.
        return ParagraphSemantic(
            "BODY_NO_INDENT", marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            classification_status="HEADING_CLASSIFICATION_NEEDS_REVIEW",
            evidence=";".join(heading_evidence) or "insufficient_structural_evidence",
        )

    if source_role == TypographyRole.FORM_LABEL.value:
        return ParagraphSemantic("FORM_LABEL", numbering_ownership=ownership, source_number_token=token, evidence="source label role")
    if item.alignment_hint == "center":
        return ParagraphSemantic(
            "BODY_CENTER", marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            evidence="source centered body geometry",
        )
    if item.alignment_hint == "right":
        return ParagraphSemantic(
            "BODY_RIGHT", marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            evidence="source right-aligned body geometry",
        )
    if float(getattr(item, "first_line_indent_pt", 0.0) or 0.0) >= 8.0:
        return ParagraphSemantic(
            "BODY_FIRST_LINE", marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            evidence="source first-line indentation",
        )
    if item.kind == "Caption":
        return ParagraphSemantic(
            "BODY_NO_INDENT", marker=marker, numbering_family=family,
            numbering_ownership=ownership, source_number_token=token,
            evidence="short source caption",
        )
    return ParagraphSemantic(
        "BODY", marker=marker, numbering_family=family,
        numbering_ownership=ownership, source_number_token=token,
        evidence="dominant source body role",
    )


def _normal_font(raw: str) -> tuple[str, bool]:
    return normalize_pdf_font_name(raw or "宋体")


def _dominant_run(records: Iterable[tuple[ParagraphSemantic, Any]]) -> tuple[str, str, float, str, bool, bool, int, int]:
    counts: Counter[tuple[str, str, float, str, bool, bool]] = Counter()
    evidence_count = 0
    evidence_weight = 0
    for _semantic, item in records:
        text_weight = max(1, len(_compact(getattr(item, "logical_text", ""))))
        for run in getattr(getattr(item, "source", None), "runs", []) or []:
            if not run.text.strip():
                continue
            family, _changed = _normal_font(run.font_name)
            size = round(float(run.font_size or 10.5), 2)
            weight = str(run.font_weight_role or ("bold" if run.bold else "regular"))
            key = (family, run.font_name or family, size, weight, bool(run.bold), bool(run.italic))
            counts[key] += max(1, len(run.text)) * text_weight
            evidence_count += 1
            evidence_weight += max(1, len(run.text))
    if not counts:
        return "宋体", "宋体", 10.5, "regular", False, False, 0, 0
    family, raw, size, weight, bold, italic = counts.most_common(1)[0][0]
    return family, raw, size, weight, bold, italic, evidence_count, evidence_weight


def _records_for(template: SourceFormatTemplate, layouts: list[Any]) -> list[tuple[ParagraphSemantic, Any, Any]]:
    toc_pages = _toc_pages(template)
    toc_entries = _toc_entries(template)
    records: list[tuple[ParagraphSemantic, Any, Any]] = []
    for page, layout in zip(template.source_pages, layouts):
        for item in layout.elements:
            if hasattr(item, "row_geometries"):
                neighbors = [row.item for row in item.row_geometries]
                for row in item.row_geometries:
                    semantic = classify_paragraph(
                        row.item, page, layout_classification=layout.classification,
                        toc_pages=toc_pages, toc_entries=toc_entries,
                        neighboring_items=neighbors,
                    )
                    records.append((semantic, row.item, page))
            elif hasattr(item, "source"):
                semantic = classify_paragraph(
                    item, page, layout_classification=layout.classification,
                    toc_pages=toc_pages, toc_entries=toc_entries,
                    neighboring_items=[candidate for candidate in layout.elements if hasattr(candidate, "source")],
                )
                records.append((semantic, item, page))
    return records


def _role_style(
    role: str,
    records: list[tuple[ParagraphSemantic, Any, Any]],
    fallback: RoleStyle | None = None,
    *,
    based_on: str = "Normal",
    outline_level: int | None = None,
    keep_with_next: bool = False,
    visual_weights: dict[str, bool] | None = None,
    visual_role: str | None = None,
) -> RoleStyle:
    selected = [(semantic, item) for semantic, item, _page in records if semantic.role == role]
    base = fallback or RoleStyle(based_on=based_on)
    family, raw, size, weight, bold, italic, count, char_weight = _dominant_run(selected)
    # Round 5.6: rendered glyph weight outranks PDF span flags.  A tender source
    # can render an emphatic role in a regular face, so the measured visual role
    # decides the delivered Word weight instead of the font metadata.
    measured = (visual_weights or _VISUAL_WEIGHTS.get() or {}).get(visual_role or role)
    if measured is not None:
        bold = bool(measured)
        weight = "bold" if bold else "regular"
    if not selected:
        return RoleStyle(**{**base.as_dict(), "bold": None}) if False else base
    alignments = Counter(
        getattr(item, "alignment_hint", None) or getattr(getattr(item, "source", None), "alignment", "left")
        for _semantic, item in selected
    )
    alignment = alignments.most_common(1)[0][0] if alignments else base.paragraph_alignment
    pitches = [
        float(getattr(item, "line_pitch_pt", 0.0) or 0.0)
        for _semantic, item in selected
        if float(getattr(item, "line_pitch_pt", 0.0) or 0.0) > 0
    ]
    first_lines = [
        float(getattr(item, "first_line_indent_pt", 0.0) or 0.0)
        for _semantic, item in selected
    ]
    return RoleStyle(
        font_east_asia=family,
        font_ascii="Times New Roman",
        source_font_raw=raw,
        font_size=size,
        font_weight="bold" if bold or weight == "bold" else weight,
        paragraph_alignment=alignment,
        line_spacing=round(median(pitches or [base.line_spacing]), 2),
        space_before=base.space_before,
        space_after=base.space_after,
        left_indent=base.left_indent,
        right_indent=base.right_indent,
        first_line_indent=round(median(first_lines or [base.first_line_indent]), 2),
        hanging_indent=base.hanging_indent,
        page_break_before=base.page_break_before,
        keep_with_next=keep_with_next,
        keep_lines=keep_with_next,
        outline_level=outline_level,
        based_on=based_on,
        evidence_count=count,
        evidence_weight=char_weight,
    )


def infer_tender_style_profile(
    template: SourceFormatTemplate,
    layouts: list[Any] | None = None,
    *,
    visual_weights: dict[str, bool] | None = None,
) -> TenderStyleProfile:
    """Cluster source spans by role and return a visual profile.

    ``visual_weights`` carries the ROUND 5.6 rendered-glyph weight verdict per
    semantic role (``{"TOC_TITLE": True, "HEADING_1": True, ...}``).  The
    measurement is taken from the rendered source page, so it overrides the
    font flags the PDF exposes.
    """

    token = _VISUAL_WEIGHTS.set(dict(visual_weights or {}))
    try:
        return _infer_tender_style_profile(template, layouts)
    finally:
        _VISUAL_WEIGHTS.reset(token)


def _infer_tender_style_profile(
    template: SourceFormatTemplate,
    layouts: list[Any] | None = None,
) -> TenderStyleProfile:
    """Cluster source spans by role and return a visual profile."""

    if layouts is None:
        from .page_layout import build_page_layout

        layouts = [build_page_layout(page) for page in template.source_pages]
    records = _records_for(template, layouts)
    body_records = [record for record in records if record[0].role in {
        "BODY", "BODY_FIRST_LINE", "BODY_CENTER", "BODY_RIGHT", "BODY_NO_INDENT"
    }]
    body = _role_style("BODY", records, based_on="Normal")
    if not body_records:
        body = _role_style("BODY_CENTER", records, based_on="Normal")

    roles: dict[str, RoleStyle] = {"Body": body}
    for semantic_role, public_name, base_name in (
        ("BODY_FIRST_LINE", "Body First Line", "正文（首行缩进两字）"),
        ("BODY_CENTER", "Body Center", "正文居中"),
        ("BODY_RIGHT", "Body Right", "正文靠右"),
        ("BODY_NO_INDENT", "Body No Indent", "Normal"),
        ("FORM_LABEL", "Form Label", "Normal"),
        ("SIGNATURE_BLOCK", "Signature Block", "正文（首行缩进两字）"),
        ("CHAPTER_TITLE", "Chapter Title", "正文居中"),
        ("COVER_PROJECT_TITLE", "Cover Project Title", "正文居中"),
        ("DOCUMENT_TITLE", "Document Title", "正文居中"),
        ("TOC_TITLE", "TOC Title", "正文居中"),
        ("TOC_1", "TOC 1", "Normal"),
        ("TOC_2", "TOC 2", "Normal"),
        ("TOC_3", "TOC 3", "Normal"),
    ):
        roles[public_name] = _role_style(
            semantic_role, records, body, based_on=base_name,
        )
    for level in range(1, 10):
        selected_headings = [
            (semantic, item, page) for semantic, item, page in records
            if semantic.role == "HEADING" and semantic.heading_level == level
        ]
        heading_style = _role_style(
            "HEADING", selected_headings or records,
            body,
            based_on="Normal",
            outline_level=level - 1,
            keep_with_next=True,
            visual_role=f"HEADING_{level}",
        )
        if selected_headings:
            heading_one = roles.get("Heading 1")
            if level > 1 and heading_one is not None:
                # Sparse subheading evidence often contains a long body-like
                # extractor span. When it conflicts with a clearly distinct
                # heading family, retain the family established by Heading 1.
                if (
                    heading_one.font_east_asia != body.font_east_asia
                    and heading_style.font_east_asia == body.font_east_asia
                ):
                    heading_style.font_east_asia = heading_one.font_east_asia
                    heading_style.source_font_raw = heading_one.source_font_raw
                    heading_style.font_weight = heading_one.font_weight
                observed_sizes = [
                    float(run.font_size or 0.0)
                    for _semantic, item, _page in selected_headings
                    for run in getattr(getattr(item, "source", None), "runs", []) or []
                    if float(run.font_size or 0.0) > 0
                ]
                if (
                    observed_sizes
                    and heading_one.font_size > body.font_size
                    and heading_style.font_size <= body.font_size
                ):
                    heading_style.font_size = round(max(observed_sizes), 2)
        roles[f"Heading {level}"] = heading_style
    for level in range(4):
        selected = [
            (semantic, item, page) for semantic, item, page in records
            if semantic.role == "BODY_LIST" and semantic.list_level == level
        ]
        list_style = _role_style(
            "BODY_LIST", selected or records, body,
            based_on="Tender Body", keep_with_next=False,
        )
        if selected:
            left = [max(0.0, float(getattr(item, "left_indent_pt", 0.0)) - 18.0) for _s, item, _p in selected]
            hanging = [abs(float(getattr(item, "first_line_indent_pt", 0.0) or 0.0)) for _s, item, _p in selected]
            list_style.left_indent = round(median(left or [18.0]) + level * 18.0, 2)
            list_style.hanging_indent = round(median(hanging or [18.0]), 2)
            list_style.first_line_indent = -list_style.hanging_indent
        list_style.based_on = "Tender Body"
        roles[f"Body List {level + 1}"] = list_style

    table_records: list[tuple[ParagraphSemantic, Any, Any]] = []
    for page in template.source_pages:
        for table in page.tables:
            for row in table.rows:
                for cell in row.cells:
                    table_records.append((ParagraphSemantic("TABLE_TEXT"), cell, page))
    table_body = _role_style("TABLE_TEXT", table_records, body, based_on="Table Text")
    roles["Table Text"] = table_body
    for cell_role, public_name in (
        ("HEADER", "Table Header"), ("BODY_TEXT", "Table Value"),
        ("NUMERIC", "Table Numeric"), ("UNIT", "Table Unit"),
    ):
        selected = [
            (semantic, cell, page) for semantic, cell, page in table_records
            if getattr(cell, "cell_role", "BODY_TEXT") == cell_role
        ]
        roles[public_name] = _role_style("TABLE_TEXT", selected or table_records, table_body, based_on="Table Text")
        roles[public_name].paragraph_alignment = (
            "center" if cell_role in {"HEADER", "NUMERIC", "UNIT"} else "left"
        )

    body_formats: dict[int, str] = {}
    body_markers: dict[int, str] = {}
    for semantic, item, _page in records:
        if semantic.role != "BODY_LIST" or semantic.marker in body_markers.values():
            continue
        level = semantic.list_level or 0
        marker = semantic.marker
        if re.fullmatch(r"\d+[、]", marker):
            fmt = f"%{level + 1}、"
        elif re.fullmatch(r"\d+[．.]", marker):
            fmt = f"%{level + 1}."
        elif re.fullmatch(r"[（(]\d+[）)]", marker):
            fmt = f"（%{level + 1}）"
        elif re.fullmatch(r"[（(][一二三四五六七八九十]+[）)]", marker):
            fmt = f"（%{level + 1}）"
        else:
            fmt = f"%{level + 1}."
        body_formats.setdefault(level, fmt)
        body_markers.setdefault(level, marker)
    for level in range(4):
        body_formats.setdefault(level, f"%{level + 1}.")
        body_markers.setdefault(level, "1.")

    heading_formats: dict[int, str] = {}
    heading_markers: dict[int, str] = {}
    for semantic, _item, _page in records:
        if semantic.role != "HEADING" or semantic.source_number_token is None:
            continue
        token = semantic.source_number_token
        level = max(0, min(8, (semantic.heading_level or token.normalized_level_hint or 1) - 1))
        marker = token.marker
        if token.numbering_family == "CHINESE_CLAUSE":
            fmt = f"%{level + 1}、"
        elif token.numbering_family == "CHINESE_PAREN":
            fmt = f"（%{level + 1}）"
        elif token.numbering_family == "DECIMAL":
            fmt = ".".join(f"%{index + 1}" for index in range(level + 1)) + "."
        elif token.numbering_family == "DECIMAL_PAREN":
            fmt = f"（%{level + 1}）"
        else:
            fmt = f"%{level + 1}."
        heading_formats.setdefault(level, fmt)
        heading_markers.setdefault(level, marker)
    default_heading_formats = {
        0: "%1、", 1: "（%2）", 2: "%3.", 3: "%3.%4.",
        4: "%3.%4.%5.", 5: "%3.%4.%5.%6.",
    }
    for level in range(9):
        heading_formats.setdefault(level, default_heading_formats.get(level, f"%{level + 1}."))
        heading_markers.setdefault(level, "1.")

    return TenderStyleProfile(
        source_file=getattr(getattr(template, "source_type", None), "value", ""),
        roles=roles,
        body_list_formats=body_formats,
        body_list_source_markers=body_markers,
        heading_numbering_formats=heading_formats,
        heading_numbering_source_markers=heading_markers,
    )


def _style_by_name(document: Document, name: str):
    for style in document.styles:
        if style.name == name:
            return style
    return None


def _ensure_style(document: Document, name: str, base_name: str = "Normal"):
    style = _style_by_name(document, name)
    if style is None:
        style = document.styles.add_style(name, WD_STYLE_TYPE.PARAGRAPH)
    base = _style_by_name(document, base_name)
    if base is not None and style is not base:
        style.base_style = base
    return style


def _ensure_table_grid_style(document: Document) -> None:
    """Provide the familiar editable grid when the fixture omits it.

    The supplied fixture intentionally contains only its structural styles and
    has no ``Table Grid`` table style.  Source tables still need visible,
    editable cell rules, so add the small standard table-style definition only
    when it is absent.  This is a table style, not a synthetic layout table.
    """
    if _style_by_name(document, "Table Grid") is not None:
        return
    style = document.styles.add_style("Table Grid", WD_STYLE_TYPE.TABLE)
    base = _style_by_name(document, "Table Normal") or _style_by_name(document, "Normal Table")
    if base is not None:
        style.base_style = base
    tbl_pr = OxmlElement("w:tblPr")
    tbl_ind = OxmlElement("w:tblInd")
    tbl_ind.set(qn("w:w"), "0")
    tbl_ind.set(qn("w:type"), "dxa")
    tbl_pr.append(tbl_ind)
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        border = OxmlElement(f"w:{edge}")
        border.set(qn("w:val"), "single")
        border.set(qn("w:sz"), "4")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "auto")
        borders.append(border)
    tbl_pr.append(borders)
    style._element.append(tbl_pr)


def _set_style_fonts(style, role: RoleStyle) -> None:
    style.font.name = role.font_ascii
    style._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:ascii"), role.font_ascii)
    style._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:hAnsi"), role.font_ascii)
    style._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:eastAsia"), role.font_east_asia)
    style.font.size = Pt(max(1.0, min(1638.0, role.font_size)))
    style.font.bold = role.bold
    style.font.italic = role.font_weight == "italic"
    style.font.color.rgb = RGBColor(0, 0, 0)


def _apply_style_values(style, role: RoleStyle) -> None:
    _set_style_fonts(style, role)
    pf = style.paragraph_format
    pf.alignment = ALIGNMENT_VALUES.get(role.paragraph_alignment, WD_ALIGN_PARAGRAPH.LEFT)
    pf.line_spacing = infer_semantic_line_spacing(
        role.font_size, role.line_spacing,
    ).word_value
    pf.space_before = Pt(max(0.0, role.space_before))
    pf.space_after = Pt(max(0.0, role.space_after))
    pf.left_indent = Pt(max(0.0, role.left_indent))
    pf.right_indent = Pt(max(0.0, role.right_indent))
    pf.first_line_indent = Pt(role.first_line_indent)
    pf.keep_with_next = role.keep_with_next
    pf.keep_together = role.keep_lines
    pf.page_break_before = role.page_break_before
    pf.widow_control = False


def _style_ppr(style):
    return style._element.get_or_add_pPr()


def _remove_style_numbering(style) -> None:
    """Detach automatic numbering from a source-owned named style."""

    ppr = style._element.find(qn("w:pPr"))
    if ppr is not None:
        num_pr = ppr.find(qn("w:numPr"))
        if num_pr is not None:
            ppr.remove(num_pr)


def _set_style_outline_level(style, level: int | None) -> None:
    if level is None:
        return
    ppr = _style_ppr(style)
    outline = ppr.find(qn("w:outlineLvl"))
    if outline is None:
        outline = OxmlElement("w:outlineLvl")
        ppr.append(outline)
    outline.set(qn("w:val"), str(max(0, min(8, level))))


def _set_style_numbering(style, num_id: int, level: int) -> None:
    """Attach real Word numbering only to a GENERATED_AUTO style."""

    ppr = _style_ppr(style)
    old = ppr.find(qn("w:numPr"))
    if old is not None:
        ppr.remove(old)
    num_pr = OxmlElement("w:numPr")
    ilvl = OxmlElement("w:ilvl")
    ilvl.set(qn("w:val"), str(max(0, min(8, level))))
    num_pr.append(ilvl)
    num = OxmlElement("w:numId")
    num.set(qn("w:val"), str(num_id))
    num_pr.append(num)
    after_num_pr = {
        "suppressLineNumbers", "pBdr", "shd", "tabs", "suppressAutoHyphens",
        "kinsoku", "wordWrap", "overflowPunct", "topLinePunct", "autoSpaceDE",
        "autoSpaceDN", "bidi", "adjustRightInd", "snapToGrid", "spacing", "ind",
        "contextualSpacing", "mirrorIndents", "suppressOverlap", "jc", "textDirection",
        "textAlignment", "textboxTightWrap", "outlineLvl", "divId", "cnfStyle", "rPr",
        "sectPr", "pPrChange",
    }
    insert_at = len(ppr)
    for index, child in enumerate(ppr):
        if child.tag.rsplit("}", 1)[-1] in after_num_pr:
            insert_at = index
            break
    ppr.insert(insert_at, num_pr)


def _strip_body_content(document: Document) -> None:
    body = document._element.body
    sect_pr = body.sectPr
    for child in list(body):
        if child is not sect_pr:
            body.remove(child)


def _numbering_root(document: Document):
    return document.part.numbering_part.element


def _max_numbering_id(document: Document, tag: str, attr: str) -> int:
    values = []
    for element in _numbering_root(document).findall(qn(f"w:{tag}")):
        value = element.get(qn(f"w:{attr}"))
        if value is not None and value.isdigit():
            values.append(int(value))
    return max(values, default=0)


def add_body_list_numbering(document: Document, profile: TenderStyleProfile) -> int:
    """Add one GENERATED_AUTO multilevel numbering definition for body lists."""

    numbering = _numbering_root(document)
    abstract_id = _max_numbering_id(document, "abstractNum", "abstractNumId") + 1
    num_id = _max_numbering_id(document, "num", "numId") + 1
    abstract = OxmlElement("w:abstractNum")
    abstract.set(qn("w:abstractNumId"), str(abstract_id))
    nsid = OxmlElement("w:nsid")
    nsid.set(qn("w:val"), f"{abstract_id + 500:08X}"[-8:])
    abstract.append(nsid)
    multi = OxmlElement("w:multiLevelType")
    multi.set(qn("w:val"), "multilevel")
    abstract.append(multi)
    tmpl = OxmlElement("w:tmpl")
    tmpl.set(qn("w:val"), f"{num_id + 700:08X}"[-8:])
    abstract.append(tmpl)
    for level in range(4):
        lvl = OxmlElement("w:lvl")
        lvl.set(qn("w:ilvl"), str(level))
        start = OxmlElement("w:start")
        start.set(qn("w:val"), "1")
        lvl.append(start)
        fmt = OxmlElement("w:numFmt")
        fmt.set(qn("w:val"), "decimal")
        lvl.append(fmt)
        text = OxmlElement("w:lvlText")
        text.set(qn("w:val"), profile.body_list_formats.get(level, f"%{level + 1}."))
        lvl.append(text)
        jc = OxmlElement("w:lvlJc")
        jc.set(qn("w:val"), "left")
        lvl.append(jc)
        ppr = OxmlElement("w:pPr")
        tabs = OxmlElement("w:tabs")
        tab = OxmlElement("w:tab")
        tab.set(qn("w:val"), "num")
        tab.set(qn("w:pos"), str(720 + level * 360))
        tabs.append(tab)
        ppr.append(tabs)
        ind = OxmlElement("w:ind")
        ind.set(qn("w:left"), str(720 + level * 360))
        ind.set(qn("w:hanging"), str(360))
        ppr.append(ind)
        lvl.append(ppr)
        abstract.append(lvl)
    first_num = next((index for index, child in enumerate(numbering) if child.tag == qn("w:num")), None)
    if first_num is None:
        numbering.append(abstract)
    else:
        numbering.insert(first_num, abstract)
    num = OxmlElement("w:num")
    num.set(qn("w:numId"), str(num_id))
    abstract_ref = OxmlElement("w:abstractNumId")
    abstract_ref.set(qn("w:val"), str(abstract_id))
    num.append(abstract_ref)
    numbering.append(num)
    return num_id


def add_generated_heading_numbering_family(document: Document, profile: TenderStyleProfile) -> int:
    """Add a generated heading family learned from source conventions."""

    numbering = _numbering_root(document)
    abstract_id = _max_numbering_id(document, "abstractNum", "abstractNumId") + 1
    num_id = _max_numbering_id(document, "num", "numId") + 1
    abstract = OxmlElement("w:abstractNum")
    abstract.set(qn("w:abstractNumId"), str(abstract_id))
    nsid = OxmlElement("w:nsid")
    nsid.set(qn("w:val"), f"{abstract_id + 900:08X}"[-8:])
    abstract.append(nsid)
    multi = OxmlElement("w:multiLevelType")
    multi.set(qn("w:val"), "multilevel")
    abstract.append(multi)
    for level in range(9):
        lvl = OxmlElement("w:lvl")
        lvl.set(qn("w:ilvl"), str(level))
        start = OxmlElement("w:start")
        start.set(qn("w:val"), "1")
        lvl.append(start)
        fmt_text = profile.heading_numbering_formats.get(level, f"%{level + 1}.")
        fmt = OxmlElement("w:numFmt")
        fmt.set(qn("w:val"), "chineseCounting" if "、" in fmt_text else "decimal")
        lvl.append(fmt)
        text = OxmlElement("w:lvlText")
        text.set(qn("w:val"), fmt_text)
        lvl.append(text)
        jc = OxmlElement("w:lvlJc")
        jc.set(qn("w:val"), "left")
        lvl.append(jc)
        ppr = OxmlElement("w:pPr")
        ind = OxmlElement("w:ind")
        ind.set(qn("w:left"), str(720 + level * 360))
        ind.set(qn("w:hanging"), "360")
        ppr.append(ind)
        lvl.append(ppr)
        abstract.append(lvl)
    first_num = next((index for index, child in enumerate(numbering) if child.tag == qn("w:num")), None)
    if first_num is None:
        numbering.append(abstract)
    else:
        numbering.insert(first_num, abstract)
    num = OxmlElement("w:num")
    num.set(qn("w:numId"), str(num_id))
    abstract_ref = OxmlElement("w:abstractNumId")
    abstract_ref.set(qn("w:val"), str(abstract_id))
    num.append(abstract_ref)
    numbering.append(num)
    return num_id


def _add_num_pr(paragraph, num_id: int, level: int) -> None:
    ppr = paragraph._p.get_or_add_pPr()
    old = ppr.find(qn("w:numPr"))
    if old is not None:
        ppr.remove(old)
    num_pr = OxmlElement("w:numPr")
    ilvl = OxmlElement("w:ilvl")
    ilvl.set(qn("w:val"), str(max(0, min(8, level))))
    num_pr.append(ilvl)
    num = OxmlElement("w:numId")
    num.set(qn("w:val"), str(num_id))
    num_pr.append(num)
    # CT_PPr places numPr before spacing/ind/jc.  Appending it after the
    # visual properties is accepted by python-docx but is not schema-ordered
    # and makes Word-safety forensics report a false regression.
    after_num_pr = {
        "suppressLineNumbers", "pBdr", "shd", "tabs", "suppressAutoHyphens",
        "kinsoku", "wordWrap", "overflowPunct", "topLinePunct", "autoSpaceDE",
        "autoSpaceDN", "bidi", "adjustRightInd", "snapToGrid", "spacing", "ind",
        "contextualSpacing", "mirrorIndents", "suppressOverlap", "jc", "textDirection",
        "textAlignment", "textboxTightWrap", "outlineLvl", "divId", "cnfStyle", "rPr",
        "sectPr", "pPrChange",
    }
    insert_at = len(ppr)
    for index, child in enumerate(ppr):
        if child.tag.rsplit("}", 1)[-1] in after_num_pr:
            insert_at = index
            break
    ppr.insert(insert_at, num_pr)


class FixtureStylePack:
    """Load the fixture, retain its style/numbering package, and restyle it."""

    def __init__(self, fixture_path: str | Path | None = None):
        path = Path(fixture_path or FIXTURE_DEFAULT_PATH)
        self.fixture_path = path if path.is_file() else None
        self.fixture_sha256 = hashlib.sha256(path.read_bytes()).hexdigest() if self.fixture_path else None
        self.heading_num_id = 1
        self.generated_heading_num_id: int | None = None
        self.generated_body_list_num_id: int | None = None
        self.baseline_style_names: list[str] = []
        self.baseline_style_ids: dict[str, str] = {}
        self.baseline_numbering: dict[str, Any] = {}
        if self.fixture_path:
            self._inspect_fixture()

    def _inspect_fixture(self) -> None:
        with ZipFile(self.fixture_path) as archive:
            styles = etree.fromstring(archive.read("word/styles.xml"))
            numbering = etree.fromstring(archive.read("word/numbering.xml"))
        for style in styles.xpath("./w:style[@w:type='paragraph']", namespaces=W):
            style_id = style.get(f"{{{W_NS}}}styleId", "")
            name = next(iter(style.xpath("./w:name/@w:val", namespaces=W)), "")
            self.baseline_style_names.append(name)
            self.baseline_style_ids[name] = style_id
        heading = next(
            iter(styles.xpath("./w:style[w:name/@w:val='heading 1']/w:pPr/w:numPr/w:numId/@w:val", namespaces=W)),
            None,
        )
        if heading and str(heading).isdigit():
            self.heading_num_id = int(heading)
        abstract = next(iter(numbering.xpath("./w:abstractNum", namespaces=W)), None)
        self.baseline_numbering = {
            "abstract_num_id": abstract.get(f"{{{W_NS}}}abstractNumId") if abstract is not None else None,
            "levels": [
                {
                    "level": level.get(f"{{{W_NS}}}ilvl"),
                    "format": next(iter(level.xpath("./w:numFmt/@w:val", namespaces=W)), None),
                    "text": next(iter(level.xpath("./w:lvlText/@w:val", namespaces=W)), None),
                }
                for level in (abstract.xpath("./w:lvl", namespaces=W) if abstract is not None else [])
            ],
            "num_id": str(self.heading_num_id),
        }

    def new_document(self) -> Document:
        # The fixture is evidence for style and numbering concepts only.
        # Loading it as the output package imports settings.xml and other
        # package-owned state. Its note settings survived after note
        # relationships were removed and made desktop Word repair note-free
        # output. Always author a fresh package; apply_profile recreates the
        # accepted editable style concepts below.
        document = Document()
        clean_bootstrap(document)
        # The fixture is a structural baseline.  The generated document's
        # title/content metadata belongs to this run, not to the fixture.
        document.core_properties.title = "基础投标文件"
        document.core_properties.author = "WorkBuddyTenderSkill"
        document.core_properties.subject = "Fresh-package tender style architecture"
        document.core_properties.comments = ""
        document.core_properties.last_modified_by = ""
        document.core_properties.keywords = ""
        return document

    def apply_profile(self, document: Document, profile: TenderStyleProfile) -> dict[str, Any]:
        # Preserve the fixture's editable heading hierarchy and outline
        # semantics, but detach its automatic numbering from source-owned
        # Heading styles. The fixture numbering machinery is re-used only by
        # explicitly generated styles below.
        _ensure_table_grid_style(document)
        for level in range(1, 10):
            style = _ensure_style(document, f"Heading {level}", "Normal")
            _apply_style_values(style, profile.role(f"Heading {level}"))
            _remove_style_numbering(style)
            _set_style_outline_level(style, profile.role(f"Heading {level}").outline_level or level - 1)
        for name, base_name in STYLE_BASELINES.items():
            style = _ensure_style(document, name, base_name)
            role_key = {
                "Tender Body": "Body", "Tender Body First Line": "Body First Line",
                "Tender Body Center": "Body Center", "Tender Body Right": "Body Right",
                "Tender Body No Indent": "Body No Indent", "Tender Signature Block": "Signature Block",
                "Tender Form Label": "Form Label", "Tender Chapter Title": "Chapter Title",
                "Tender Cover Project Title": "Cover Project Title", "Tender Document Title": "Document Title",
                "Tender TOC Title": "TOC Title", "Tender TOC 1": "TOC 1", "Tender TOC 2": "TOC 2",
                "Tender TOC 3": "TOC 3", "Table Text": "Table Text", "Tender Table Header": "Table Header",
                "Tender Table Label": "Table Label", "Tender Table Value": "Table Value",
                "Tender Table Numeric": "Table Numeric", "Tender Table Unit": "Table Unit",
            }.get(name, name)
            _apply_style_values(style, profile.role(role_key))
        for level in range(1, 5):
            style = _ensure_style(document, f"Tender Body List {level}", "Tender Body")
            _apply_style_values(style, profile.role(f"Body List {level}"))

        self.generated_heading_num_id = add_generated_heading_numbering_family(document, profile)
        self.generated_body_list_num_id = add_body_list_numbering(document, profile)
        for level in range(1, 10):
            style = _ensure_style(document, f"Tender Generated Heading {level}", f"Heading {level}")
            _apply_style_values(style, profile.role(f"Heading {level}"))
            _set_style_outline_level(style, profile.role(f"Heading {level}").outline_level or level - 1)
            _set_style_numbering(style, self.generated_heading_num_id, level - 1)
        for level in range(1, 5):
            style = _ensure_style(document, f"Tender Generated Body List {level}", f"Tender Body List {level}")
            _apply_style_values(style, profile.role(f"Body List {level}"))
            _set_style_numbering(style, self.generated_body_list_num_id, level - 1)

        return {
            "fixture_path": str(self.fixture_path) if self.fixture_path else None,
            "fixture_sha256": self.fixture_sha256,
            "baseline_style_names": self.baseline_style_names,
            "baseline_style_ids": self.baseline_style_ids,
            "baseline_numbering": self.baseline_numbering,
            "preserved_concepts": {
                "style_inheritance": True,
                "outline_levels": True,
                "heading_hierarchy": True,
                "source_heading_styles_have_no_auto_numbering": True,
                "generated_auto_numbering_family": True,
                "body_first_line_style": _style_by_name(document, "正文（首行缩进两字）") is not None,
                "body_center_style": _style_by_name(document, "正文居中") is not None,
                "body_right_style": _style_by_name(document, "正文靠右") is not None,
                "table_text_style": _style_by_name(document, "Table Text") is not None,
            },
            "numbering_ownership": {
                "source_heading_styles": NumberingOwnership.SOURCE_LITERAL.value,
                "source_body_list_styles": NumberingOwnership.SOURCE_LITERAL.value,
                "generated_heading_styles": NumberingOwnership.GENERATED_AUTO.value,
                "generated_body_list_styles": NumberingOwnership.GENERATED_AUTO.value,
                "generated_heading_num_id": self.generated_heading_num_id,
                "generated_body_list_num_id": self.generated_body_list_num_id,
            },
            "visual_properties_intentionally_changed": sorted(profile.roles),
        }


def set_paragraph_style(paragraph: Any, style_name: str) -> None:
    paragraph.style = style_name


def add_structural_numbering(paragraph: Any, style_pack: FixtureStylePack, level: int) -> None:
    """Add GENERATED_AUTO numbering to a generated heading paragraph."""

    _add_num_pr(paragraph, style_pack.generated_heading_num_id or style_pack.heading_num_id, level - 1)


def add_body_numbering(paragraph: Any, num_id: int, level: int) -> None:
    """Add GENERATED_AUTO numbering to a generated body-list paragraph."""

    _add_num_pr(paragraph, num_id, level)


def add_generated_heading_numbering(paragraph: Any, style_pack: FixtureStylePack, level: int) -> None:
    """Explicit name for generated heading numbering used by new callers."""

    add_structural_numbering(paragraph, style_pack, level)


def fixture_integrity_report(style_pack: FixtureStylePack, profile: TenderStyleProfile) -> dict[str, Any]:
    return {
        "fixture_style_baseline": {
            "path": str(style_pack.fixture_path) if style_pack.fixture_path else None,
            "sha256": style_pack.fixture_sha256,
            "heading_num_id": style_pack.heading_num_id,
            "generated_heading_num_id": style_pack.generated_heading_num_id,
            "generated_body_list_num_id": style_pack.generated_body_list_num_id,
            "baseline_style_names": style_pack.baseline_style_names,
            "baseline_numbering": style_pack.baseline_numbering,
        },
        "preserved_concepts": {
            "style_inheritance": True,
            "outline_levels": True,
            "heading_hierarchy": True,
            "source_heading_styles_have_no_auto_numbering": True,
            "generated_auto_numbering_family": True,
            "body_first_line_style": True,
            "body_center_right_styles": True,
            "table_text_style": True,
        },
        "visual_properties_changed_from_fixture": sorted(profile.roles),
        "change_reason": "source tender PDF dominant semantic-role clusters",
    }


__all__ = [
    "FIXTURE_DEFAULT_PATH", "FixtureStylePack", "ParagraphSemantic", "RoleStyle",
    "TenderStyleProfile", "add_body_list_numbering", "add_body_numbering",
    "add_generated_heading_numbering", "add_generated_heading_numbering_family",
    "add_structural_numbering", "classify_paragraph", "fixture_integrity_report",
    "heading_level_for_marker", "infer_tender_style_profile", "marker_info",
    "set_paragraph_style",
]
